name: Main CI

on:
  push:
    branches: [ main ]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 5.0.200

    - name: Restore NuGet Packages
      run: dotnet restore $env:SOLUTION_PATH --configfile $env:NUGETCONFIG_PATH --runtime any
      env:
        SOLUTION_PATH: ReportingOnLinux\ReportingOnLinux.sln
        NUGETCONFIG_PATH: ReportingOnLinux\nuget.config
        CONFIGURATION: Debug
        TELERIK_USERNAME: ${{ secrets.MyTelerikAccountUsername }}
        TELERIK_PASSWORD: ${{ secrets.MyTelerikAccountPassword }}

    - name: Build Solution
      run: dotnet build $env:SOLUTION_PATH --configuration $env:CONFIGURATION --no-restore
      env:
        SOLUTION_PATH: ReportingOnLinux\ReportingOnLinux.sln
        CONFIGURATION: Debug

  build_wpf:
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.1
    
    - name: Setup NuGet.exe
      uses: NuGet/setup-nuget@v1.0.5
      with:
        nuget-version: 5.8.x

    - name: Restore NuGet Packages
      run: nuget restore $env:SOLUTION_PATH -ConfigFile $env:NUGETCONFIG_PATH
      env:
        SOLUTION_PATH: UploadingToWebApi\UploadingToWebApi_Wpf.sln
        NUGETCONFIG_PATH: UploadingToWebApi\nuget.config
        CONFIGURATION: Debug
        TELERIK_USERNAME: ${{ secrets.MyTelerikAccountUsername }}
        TELERIK_PASSWORD: ${{ secrets.MyTelerikAccountPassword }}

    - name: Build the WPF application
      run: msbuild $env:SOLUTION_PATH /t:Restore /p:Configuration=$env:CONFIGURATION /p:RuntimeIdentifier=win-x86
      env:
        SOLUTION_PATH: UploadingToWebApi\UploadingToWebApi_Wpf.sln
        NUGETCONFIG_PATH: UploadingToWebApi\nuget.config
        CONFIGURATION: Debug
