name: Build Main

on:
  push:
    branches:
    - main
    paths:
      - 'BlazorAndReporting/**/*'
      - 'UploadingToWebApi/**/*'
      - '.github/workflows/main.yml'
env:
  TELERIK_USERNAME: ${{ secrets.MyTelerikAccountUsername }}
  TELERIK_PASSWORD: ${{ secrets.MyTelerikAccountPassword }}
  
jobs:
  build_blazor_linux:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0

    - name: Restore NuGet Packages
      run: |
        echo checking workspace
        echo ${{ env.GITHUB_WORKSPACE }}
        dotnet restore BlazorAndReporting/BlazorAndReporting/BlazorAndReporting.csproj --configfile ./nuget.config --runtime any

    - name: Build Solution
      run: dotnet build BlazorAndReporting/BlazorAndReporting/BlazorAndReporting.csproj --configuration Debug --no-restore

  build_wpf_windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1.3
    
    - name: Setup NuGet.exe
      uses: NuGet/setup-nuget@v1.1.1
      with:
        nuget-version: 5.x

    - name: Restore NuGet Packages
      run: nuget restore UploadingToWebApi\UploadingToWebApi\UploadingToWebApi.Wpf.csproj -ConfigFile ./nuget.config -SolutionDirectory UploadingToWebApi\

    - name: Build the WPF application
      run: msbuild UploadingToWebApi\UploadingToWebApi\UploadingToWebApi.Wpf.csproj /t:Restore /p:Configuration=Debug /p:RuntimeIdentifier=win-x86

  build_web_windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1.3
    
    - name: Setup NuGet.exe
      uses: NuGet/setup-nuget@v1.1.1
      with:
        nuget-version: 5.x

    - name: Restore NuGet Packages
      run: nuget restore UploadingToWebApi\UploadingToWebApi.Web\UploadingToWebApi.Web.csproj -ConfigFile ./nuget.config -SolutionDirectory UploadingToWebApi\

    - name: Build the WPF application
      run: msbuild UploadingToWebApi\UploadingToWebApi.Web\UploadingToWebApi.Web.csproj /t:Restore /p:Configuration=Debug /p:RuntimeIdentifier=win-x86

  build_uwp_windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1.3
    
    - name: Setup NuGet.exe
      uses: NuGet/setup-nuget@v1.1.1
      with:
        nuget-version: 5.x

    - name: Restore NuGet Packages
      run: nuget restore UploadingToWebApi\UploadingToWebApi.Uwp\UploadingToWebApi.Uwp.csproj -ConfigFile ./nuget.config
    
    - name: Build UWP Project
      run: msbuild UploadingToWebApi\UploadingToWebApi.Uwp\UploadingToWebApi.Uwp.csproj /p:Platform=x64 /p:Configuration=Debug /p:AppxPackageSigningEnabled=false /p:UapAppxPackageBuildMode=CI /p:AppxBundle=Never
