name: Build Main

on:
  push:
    branches: [ main ]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 5.0.200

    - name: Restore NuGet Packages
      run: dotnet restore ReportingOnLinux/ReportingOnLinux/ReportingOnLinux.csproj --configfile ReportingOnLinux/nuget.config --runtime any
      env:
        TELERIK_USERNAME: ${{ secrets.MyTelerikAccountUsername }}
        TELERIK_PASSWORD: ${{ secrets.MyTelerikAccountPassword }}

    - name: Build Solution
      run: dotnet build ReportingOnLinux/ReportingOnLinux/ReportingOnLinux.csproj --configuration Debug --no-restore

  build_wpf:
    runs-on: windows-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true # this is to allow nuget.exe to be set to PATH
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.1
    
    - name: Setup NuGet.exe
      uses: NuGet/setup-nuget@v1.0.5
      with:
        nuget-version: 5.8.x

    - name: Restore NuGet Packages
      run: nuget restore UploadingToWebApi\UploadingToWebApi\UploadingToWebApi.Wpf.csproj -ConfigFile UploadingToWebApi\nuget.config -SolutionDirectory UploadingToWebApi\
      env:
        TELERIK_USERNAME: ${{ secrets.MyTelerikAccountUsername }}
        TELERIK_PASSWORD: ${{ secrets.MyTelerikAccountPassword }}

    - name: Build the WPF application
      run: msbuild UploadingToWebApi\UploadingToWebApi\UploadingToWebApi.Wpf.csproj /t:Restore /p:Configuration=Debug /p:RuntimeIdentifier=win-x86

  build_web:
    runs-on: windows-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true # this is to allow nuget.exe to be set to PATH
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.1
    
    - name: Setup NuGet.exe
      uses: NuGet/setup-nuget@v1.0.5
      with:
        nuget-version: 5.8.x

    - name: Restore NuGet Packages
      run: nuget restore UploadingToWebApi\UploadingToWebApi.Web\UploadingToWebApi.Web.csproj -ConfigFile UploadingToWebApi\nuget.config -SolutionDirectory UploadingToWebApi\
      env:
        TELERIK_USERNAME: ${{ secrets.MyTelerikAccountUsername }}
        TELERIK_PASSWORD: ${{ secrets.MyTelerikAccountPassword }}

    - name: Build the WPF application
      run: msbuild UploadingToWebApi\UploadingToWebApi.Web\UploadingToWebApi.Web.csproj /t:Restore /p:Configuration=Debug /p:RuntimeIdentifier=win-x86

  build_uwp:
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet Packages
      run: nuget restore UploadingToWebApi\UploadingToWebApi.Uwp\UploadingToWebApi.Uwp.csproj -ConfigFile UploadingToWebApi\nuget.config
      env:
        TELERIK_USERNAME: ${{ secrets.MyTelerikAccountUsername }}
        TELERIK_PASSWORD: ${{ secrets.MyTelerikAccountPassword }}  
    
    - name: Build UWP Project
      run: msbuild UploadingToWebApi\UploadingToWebApi.Uwp\UploadingToWebApi.Uwp.csproj /p:Platform=x64 /p:Configuration=Debug /p:AppxPackageSigningEnabled=false /p:UapAppxPackageBuildMode=CI /p:AppxBundle=Never
      env:
        TELERIK_USERNAME: ${{ secrets.MyTelerikAccountUsername }}
        TELERIK_PASSWORD: ${{ secrets.MyTelerikAccountPassword }}