name: Publish Linux Server

on:
  push:
    branches: [ release-linux ]

jobs:
  build_linux-arm64:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 5.0.200

    - name: Restore NuGet Packages
      run: dotnet restore ReportingOnLinux/ReportingOnLinux/ReportingOnLinux.csproj --configfile ReportingOnLinux/nuget.config -r linux-arm64
      env:
        TELERIK_USERNAME: ${{ secrets.MyTelerikAccountUsername }}
        TELERIK_PASSWORD: ${{ secrets.MyTelerikAccountPassword }}

    - name: Build Solution
      run: dotnet build ReportingOnLinux/ReportingOnLinux/ReportingOnLinux.csproj --configuration Release --no-restore -r linux-arm64

    - name: Publish Application
      run: dotnet publish ReportingOnLinux/ReportingOnLinux/ReportingOnLinux.csproj -f net5.0 -c Release --self-contained --no-restore -r linux-arm64

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ReportingServer_Linux-ARM64
        path: ReportingOnLinux/ReportingOnLinux/bin/Release/net5.0/
  
  build_linux-arm:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 5.0.200

    - name: Restore NuGet Packages
      run: dotnet restore ReportingOnLinux/ReportingOnLinux/ReportingOnLinux.csproj --configfile ReportingOnLinux/nuget.config -r linux-arm
      env:
        TELERIK_USERNAME: ${{ secrets.MyTelerikAccountUsername }}
        TELERIK_PASSWORD: ${{ secrets.MyTelerikAccountPassword }}

    - name: Build Solution
      run: dotnet build ReportingOnLinux/ReportingOnLinux/ReportingOnLinux.csproj --configuration Release --no-restore -r linux-arm

    - name: Publish Application
      run: dotnet publish ReportingOnLinux/ReportingOnLinux/ReportingOnLinux.csproj -f net5.0 -c Release --self-contained --no-restore -r linux-arm

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ReportingServer_Linux-ARM64
        path: ReportingOnLinux/ReportingOnLinux/bin/Release/net5.0/
  
  build_linux-x64:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 5.0.200

    - name: Restore NuGet Packages
      run: dotnet restore ReportingOnLinux/ReportingOnLinux/ReportingOnLinux.csproj --configfile ReportingOnLinux/nuget.config -r linux-x64
      env:
        TELERIK_USERNAME: ${{ secrets.MyTelerikAccountUsername }}
        TELERIK_PASSWORD: ${{ secrets.MyTelerikAccountPassword }}

    - name: Build Solution
      run: dotnet build ReportingOnLinux/ReportingOnLinux/ReportingOnLinux.csproj --configuration Release --no-restore -r linux-x64

    - name: Publish Application
      run: dotnet publish ReportingOnLinux/ReportingOnLinux/ReportingOnLinux.csproj -f net5.0 -c Release --self-contained --no-restore -r linux-x64

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ReportingServer_Linux-x64
        path: ReportingOnLinux/ReportingOnLinux/bin/Release/net5.0/