name: Publish Linux Server

on:
  push:
    branches: [ release-linux ]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 5.0.200

    - name: Restore NuGet Packages
      run: dotnet restore ReportingOnLinux/ReportingOnLinux/ReportingOnLinux.csproj --configfile ReportingOnLinux/nuget.config --runtime any
      env:
        TELERIK_USERNAME: ${{ secrets.MyTelerikAccountUsername }}
        TELERIK_PASSWORD: ${{ secrets.MyTelerikAccountPassword }}

    - name: Build Solution
      run: dotnet build ReportingOnLinux/ReportingOnLinux/ReportingOnLinux.csproj --configuration Release --no-restore

    - name: Publish Application
      run: dotnet publish ReportingOnLinux/ReportingOnLinux/ReportingOnLinux.csproj -f net5.0 -r linux-arm64 -c Release --self-contained --no-restore -o ReportingOnLinux/ReportingOnLinux/bin/Release/net5.0/publish/

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ReportingServer_NET50
        path: ReportingOnLinux/ReportingOnLinux/bin/
